DROP TABLE IF EXISTS A, B, C, D, E, F, G, R1, R2, R4 CASCADE;

CREATE TABLE A (
	a1 INT PRIMARY KEY,
	a2 INT
);

CREATE TABLE B (
	b1 INT PRIMARY KEY,
	b2 INT
);

CREATE TABLE C (
	c1 INT PRIMARY KEY,
	c2 INT
);

CREATE TABLE D (
	d1 INT PRIMARY KEY,
	d2 INT
);

CREATE TABLE F(
	f1 INT PRIMARY KEY,
	f2 INT
);

CREATE TABLE G (
	g1 INT PRIMARY KEY,
	g2 INT
);

CREATE TABLE R1 (
	r1 INT,
	r1_a1 INT REFERENCES A,
	r1_b1 INT REFERENCES B,
	r1_g1 INT NOT NULL REFERENCES G,
	PRIMARY KEY(r1_a1, r1_b1)
);

CREATE TABLE E (
	e1 INT PRIMARY KEY,
	e2 INT,
	r1_a1 INT NOT NULL,
	r1_b1 INT NOT NULL,
	FOREIGN KEY (r1_a1, r1_b1) REFERENCES R1
);

CREATE TABLE R2 (
	r2_d1 INT REFERENCES D,
	r2_c1 INT NOT NULL REFERENCES C,
	r2_r1_a1 INT,
	r2_r1_b1 INT,
	FOREIGN KEY (r2_r1_a1, r2_r1_b1) REFERENCES R1,
	PRIMARY KEY(r2_r1_a1, r2_r1_b1, r2_d1)
);

CREATE TABLE R4 (
	r4_f1 INT REFERENCES F,
	r4_r1_a1 INT,
	r4_r1_b1 INT,
	FOREIGN KEY(r4_r1_a1, r4_r1_b1) REFERENCES R1,
	PRIMARY KEY(r4_r1_a1, r4_r1_b1, r4_f1)
);

