DROP TABLE IF EXISTS A, B, C, D, E, F, G, R1 CASCADE;

CREATE TABLE A (
	a1 INTEGER PRIMARY KEY,
	a2 INTEGER
);

CREATE TABLE B (
	b1 INTEGER PRIMARY KEY,
	b2 INTEGER
);

CREATE TABLE C (
	c1 INTEGER PRIMARY KEY,
	c2 INTEGER
);

CREATE TABLE D (
	d1 INTEGER PRIMARY KEY,
	d2 INTEGER
);

CREATE TABLE G (
	g1 INTEGER PRIMARY KEY,
	g2 INTEGER
);

CREATE TABLE F (
	f1 INTEGER PRIMARY KEY,
	f2 INTEGER
);

CREATE TABLE R1 (
	r1 INTEGER,
	r1_a1 INTEGER REFERENCES A,
	r1_b1 INTEGER REFERENCES B,
	r1_c1 INTEGER REFERENCES C,
	r1_d1 INTEGER REFERENCES D,
	r1_f1 INTEGER REFERENCES F,
	r1_g1 INTEGER NOT NULL REFERENCES G,
	PRIMARY KEY(r1_a1, r1_b1, r1_c1, r1_d1)

);

CREATE TABLE E (
	e1 INTEGER PRIMARY KEY,
	e2 INTEGER,
	a1 INTEGER NOT NULL,
	b1 INTEGER NOT NULL,
	c1 INTEGER,
	d1 INTEGER,
	FOREIGN KEY (a1, b1, c1, d1) REFERENCES R1
);