DROP TABLE IF EXISTS A, B, C, D, E, F, G, R1, R2 CASCADE;

-- Práctica: 2
-- Autor: Iván Ruiz Gázquez

CREATE TABLE A (
	a1 INTEGER PRIMARY KEY,
	a2 INTEGER
);

CREATE TABLE B (
	b1 INTEGER PRIMARY KEY,
	b2 INTEGER
);

CREATE TABLE C (
	c1 INTEGER PRIMARY KEY,
	c2 INTEGER
);

CREATE TABLE D (
	d1 INTEGER PRIMARY KEY,
	d2 INTEGER
);

CREATE TABLE E (
	e1 INTEGER PRIMARY KEY,
	e2 INTEGER
);

CREATE TABLE G (
	g1 INTEGER PRIMARY KEY,
	g2 INTEGER
);

CREATE TABLE R1 (
	r1 INTEGER,
	r1_a1 INTEGER REFERENCES A,
	r1_b1 INTEGER REFERENCES B,
	r1_e1 INTEGER NOT NULL REFERENCES E,
	r1_g1 INTEGER REFERENCES G,
	PRIMARY KEY (r1_a1, r1_b1)
);

CREATE TABLE R2 (
	r2_r1_a1 INTEGER,
	r2_r1_b1 INTEGER,
	r2_c1 INTEGER REFERENCES C,
	r2_d1 INTEGER NOT NULL REFERENCES D,
	FOREIGN KEY (r2_r1_a1, r2_r1_b1) REFERENCES R1,
	PRIMARY KEY(r2_r1_a1, r2_r1_b1, r2_c1),
	UNIQUE (r2_d1, r2_r1_a1, r2_r1_b1)
);

CREATE TABLE F(
	f1 INTEGER,
	f2 INTEGER,
	r1_a1 INTEGER NOT NULL,
	r1_b1 INTEGER NOT NULL,
	FOREIGN KEY (r1_a1, r1_b1) REFERENCES R1,
	PRIMARY KEY (f1, r1_a1, r1_b1)
);
